backend:
  name: git-gateway
  branch: main

media_folder: "wp-content/uploads"
public_folder: "/wp-content/uploads" 

collections:
  - name: "pages"
    label: "Pages"
    folder: "/" 
    create: true
    slug: "{{slug}}"
    nested:
      depth: 2
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Images", name: "images", widget: "image", media_library: { allow_multiple: true } }
